### ISSUE TITLE
Support Google recaptcha V2

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/addon-recaptcha#1]

**Comment by nghuuphuoc** [comment]
@Erfane @robgnyc 
I already moved the [formvalidation's issue 1276](https://github.com/formvalidation/formvalidation/issues/1276) to that.
I will keep both of you posted with this.

**Comment by nghuuphuoc** [comment]
@Erfane @robgnyc 
Here it's http://formvalidation.io/addons/

**Comment by Erfane** [comment]
Thanks!

Erfane
