### ISSUE TITLE
Update reCaptcha example

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/addon-recaptcha#2]
_From @blackfyre on January 27, 2015 10:38_

A new version of reCapthca is out, and has a different API than the one in the example.
A revision of the example would be great :smile: 

_Copied from original issue: formvalidation/formvalidation.io#9_

**Comment by nghuuphuoc** [comment]
@blackfyre 
Here it's http://formvalidation.io/addons/

**Comment by blackfyre** [comment]
Wonderful :smile: 
Thank you!
