### ISSUE TITLE
Add localization support for reCaptcha2

### ISSUE THREAD

**Issue by budik21** [formvalidation/addon-recaptcha#3]
I would like to ask you for implementing of language parametr of reCaptcha2 add-on. Currently is no way how to localize this add-on, API from Google supports it, see https://developers.google.com/recaptcha/docs/display#explicit_render

Thanks a lot, regards
Radek Budař

**Comment by nghuuphuoc** [comment]
Thank for the suggestion. I've just released v0.2.0 which supports localization.
You can download it now from http://formvalidation.io/addons/recaptcha2/ :+1:

**Comment by budik21** [comment]
It seems to work perfect!

I have tested:
 - language option omitted: reCaptcha2 was render in default language (probably recognized by Google)
 - language set by a declarative way by a string
 - language set by a programatic way by a string
 - language set by a variable in a programmatic way

All cases have returned expected result, so you can close this issue.

One note to the end: I don't really understand, why Google doesn't respect common language code such as "cs_CZ" or  "en_US" and uses his own.

Thanks a lot for your effort!

**Comment by budik21** [comment]
Closing the issue
